<?php
return [
    'home' => 'Dashboard',

    // MASTER DATA
    'produk' => 'List Produk',
    'material' => 'List Material',
    'alatqc' => 'Alat QC',
    'bendapecah' => 'Benda Pecah Belah',
    'peralatan' => 'Peralatan Kebersihan',
    'area_kebersihan' => 'Area Kebersihan',

    // FORM QC - KEBERSIHAN & SUHU
    'suhu' => 'Pemeriksaan Suhu Ruang',
    'chiller' => 'Pemeriksaan Suhu Chiller',
    'sanitasi' => 'Pemeriksaan Sanitasi',
    'kondisikerja' => 'Kondisi Kerja Selama Produksi',
    'kebersihankaryawan' => 'Kebersihan Karyawan',
    'kebersihanperalatan' => 'Kebersihan Peralatan',
    'kebersihanruang' => 'Kebersihan Ruang Produksi',
    'kebersihanmesin' => 'Pemeriksaan Kebersihan Mesin',
    'pembuatanlarutan' => 'Pembuatan Larutan',
    'reagen' => 'Verifikasi Penggunaan Reagen Klorin',
    'residu' => 'Verifikasi Residu Klorin',
    'larutan' => 'Pembuatan Larutan Cleaning & Sanitasi',

    // FORM QC - PRODUKSI
    'pengayakan' => 'Pengayakan',
    'kekuatanmagnet' => 'Pemeriksaan Kekuatan Magnet Trap',
    'verifikasimagnet' => 'Verifikasi Magnet Trap',
    'thermometer' => 'Peneraan Thermometer',
    'timbangan' => 'Pemeriksaan Timbangan',
    'magnettrap' => 'Pemeriksaan Magnet Trap',
    'produksi' => 'Verifikasi Proses Produksi',
    'ketidaksesuaian' => 'Ketidaksesuaian Produk',
    'proses' => 'Verifikasi Proses Produksi',
    'inventaris' => 'Checklist Inventaris Peralatan QC',
    'pecahbelah' => 'Pemeriksaan Benda Mudah Pecah',
    'disposisi' => 'Disposisi Produk dan Prosedur',
    'pemusnahan' => 'Pemusnahan Barang / Produk',
    'retain' => 'Retain Sample Report',
    'gosong' => 'Laporan Roti Gosong',

    // FORM QC - PACKING
    'metal' => 'Pemeriksaan Metal Detector',
    'falserejection' => 'Monitoring False Rejection',
    'kontaminasi' => 'Kontaminasi Benda Asing',
    'sensori' => 'Sensori Finish Good',
    'pengemasan' => 'Pemeriksaan Proses Pengemasan',
    'releasepacking' => 'Release Packing',

    // FORM QC - WAREHOUSE
    'sanitasiwarehouse' => 'Pemeriksaan Sanitasi Warehouse',
    'analisis' => 'Permohonan Analisis Sampel Lab',
    'penerimaankemasan' => 'Penerimaan Kemasan',
    'pemeriksaanchemical' => 'Pemeriksaan Chemical',
    'seasoning' => 'Pemeriksaan Seasoning',
    'loading' => 'Pemeriksaan Loading Produk',

    // VERIFIKASI SPV (prefix verifikasi)
    'verifikasi-suhu' => 'Pemeriksaan Suhu Ruang',
    'verifikasi-chiller' => 'Pemeriksaan Suhu Chiller',
    'verifikasi-sanitasi' => 'Pemeriksaan Sanitasi',
    'verifikasi-kondisikerja' => 'Kondisi Kerja Selama Produksi',
    'verifikasi-kebersihankaryawan' => 'Kebersihan Karyawan',
    'verifikasi-kebersihanperalatan' => 'Kebersihan Peralatan',
    'verifikasi-kebersihanruang' => 'Kebersihan Ruang Produksi',
    'verifikasi-kebersihanmesin' => 'Pemeriksaan Kebersihan Mesin',
    'verifikasi-pembuatanlarutan' => 'Pembuatan Larutan',
    'verifikasi-reagen' => 'Verifikasi Penggunaan Reagen Klorin',
    'verifikasi-residu' => 'Verifikasi Residu Klorin',
    'verifikasi-larutan' => 'Pembuatan Larutan Cleaning & Sanitasi',
    'verifikasi-pengayakan' => 'Pengayakan',
    'verifikasi-kekuatanmagnet' => 'Pemeriksaan Kekuatan Magnet Trap',
    'verifikasi-verifikasimagnet' => 'Verifikasi Magnet Trap',
    'verifikasi-thermometer' => 'Peneraan Thermometer',
    'verifikasi-timbangan' => 'Pemeriksaan Timbangan',
    'verifikasi-magnettrap' => 'Pemeriksaan Magnet Trap',
    'verifikasi-produksi' => 'Verifikasi Proses Produksi',
    'verifikasi-ketidaksesuaian' => 'Ketidaksesuaian Produk',
    'verifikasi-proses' => 'Verifikasi Proses Produksi',
    'verifikasi-inventaris' => 'Checklist Inventaris Peralatan QC',
    'verifikasi-pecahbelah' => 'Pemeriksaan Benda Mudah Pecah',
    'verifikasi-disposisi' => 'Disposisi Produk dan Prosedur',
    'verifikasi-pemusnahan' => 'Pemusnahan Barang / Produk',
    'verifikasi-retain' => 'Retain Sample Report',
    'verifikasi-gosong' => 'Laporan Roti Gosong',
    'verifikasi-metal' => 'Pemeriksaan Metal Detector',
    'verifikasi-falserejection' => 'Monitoring False Rejection',
    'verifikasi-kontaminasi' => 'Kontaminasi Benda Asing',
    'verifikasi-sensori' => 'Sensori Finish Good',
    'verifikasi-pengemasan' => 'Pemeriksaan Proses Pengemasan',
    'verifikasi-releasepacking' => 'Release Packing',
    'verifikasi-sanitasiwarehouse' => 'Pemeriksaan Sanitasi Warehouse',
    'verifikasi-analisis' => 'Permohonan Analisis Sampel Lab',
    'verifikasi-penerimaankemasan' => 'Penerimaan Kemasan',
    'verifikasi-pemeriksaanchemical' => 'Pemeriksaan Chemical',
    'verifikasi-seasoning' => 'Pemeriksaan Seasoning',
    'verifikasi-loading' => 'Pemeriksaan Loading Produk',
];
?>